### ISSUE TITLE
Support for OAuth2.0?

### ISSUE THREAD

**Issue by Soben** [HubSpot/haPiHP#29]
Seems a little silly that the "official" API library doesn't support oAuth 2.0 :-\

**Comment by ryanwinchester** [comment]
@Soben it's abandoned, hasn't been touched in years

**Comment by ajmedway** [comment]
Why has this been abandoned?! :/

**Comment by Soben** [comment]
ajmedway,

I don't know, but I have some guesses. RyanWinchester might be a better answer to this, but the other HubSpot API he built does accomplish our needs (https://github.com/ryanwinchester/hubspot-php), the downside is that it requires a boost in PHP versioning (which was a bummer as in my case, Wordpress Plugins still are supporting earlier versions of PHP, which I can't do with the other library), so I've had to drop support for PHP 5.2-5.4 because of it.
